import { useState } from 'react'

const ERAS = [
  { year: 1970, title: 'Mainframes & punch cards', scale: 'Megabytes', detail: 'Data is entirely structured, generated by a handful of institutions, and stored on magnetic tape.' },
  { year: 1980, title: 'Relational databases rise', scale: 'Gigabytes', detail: 'RDBMS and SQL standardize structured storage for business transactions.' },
  { year: 1991, title: 'World Wide Web goes public', scale: 'Gigabytes → Terabytes', detail: 'Pages, links and early web servers start producing semi-structured HTML/log data.' },
  { year: 2004, title: 'Web 2.0 & social media', scale: 'Terabytes → Petabytes', detail: 'Facebook, blogs and user-generated content flood the web with unstructured text and images.' },
  { year: 2007, title: 'Smartphones arrive', scale: 'Petabytes', detail: 'The iPhone puts a sensor-laden data source in billions of pockets: photos, GPS, app telemetry.' },
  { year: 2010, title: '"Big Data" & Hadoop go mainstream', scale: 'Petabytes → Exabytes', detail: 'Hadoop, distributed storage and MapReduce make it economical to process web-scale data.' },
  { year: 2015, title: 'IoT & cloud data lakes', scale: 'Exabytes', detail: 'Billions of connected sensors and cheap cloud storage make streaming ingestion the norm.' },
  { year: 2020, title: 'Streaming & remote-everything', scale: 'Zettabytes', detail: 'Video conferencing, streaming media and remote work push daily generation past the zettabyte era.' },
  { year: 2025, title: 'AI-generated & edge data', scale: '180+ Zettabytes/yr', detail: 'Generative AI, edge devices and real-time analytics make data both the input and output of intelligent systems.' },
]

export default function DataTimeline() {
  const [idx, setIdx] = useState(0)
  const era = ERAS[idx]

  return (
    <div>
      <p className="lead" style={{ marginBottom: 14 }}>
        Drag the slider across five decades to see how the volume, and character, of digital data has
        evolved.
      </p>
      <input
        type="range"
        min={0}
        max={ERAS.length - 1}
        step={1}
        value={idx}
        onChange={(e) => setIdx(Number(e.target.value))}
        style={{ width: '100%' }}
      />
      <div className="row" style={{ justifyContent: 'space-between', fontSize: '.72rem', color: 'var(--muted)', marginTop: 2 }}>
        {ERAS.map((e, i) => (
          <span key={e.year} style={{ fontWeight: i === idx ? 700 : 400, color: i === idx ? 'var(--teal)' : 'var(--muted)' }}>
            {e.year}
          </span>
        ))}
      </div>

      <div className="card" style={{ marginTop: 18, background: 'var(--teal-soft)', border: '1px solid #bfe0da' }}>
        <span className="eyebrow" style={{ margin: 0 }}>
          <span className="n">{era.year}</span> {era.title}
        </span>
        <p style={{ margin: '10px 0 4px', fontSize: '1.4rem', fontFamily: 'var(--display)', fontWeight: 700 }}>
          {era.scale}
        </p>
        <p style={{ margin: 0, color: 'var(--ink-soft)' }}>{era.detail}</p>
      </div>
    </div>
  )
}
